# Generated by Django 4.0.3 on 2022-04-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
