# Generated by Django 4.0.3 on 2022-04-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clients',
            name='patronymic',
            field=models.CharField(max_length=255),
        ),
    ]
