# Generated by Django 4.0.3 on 2022-03-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=500)),
                ('type', models.CharField(default=None, max_length=500)),
                ('model', models.CharField(default=None, max_length=500)),
                ('manufacturer', models.CharField(default=None, max_length=500)),
                ('material', models.CharField(default=None, max_length=500)),
                ('color', models.CharField(default=None, max_length=500)),
                ('price', models.DecimalField(decimal_places=9, default=None, max_digits=10)),
                ('description', models.CharField(default=None, max_length=500)),
                ('photo_file_name', models.CharField(default=None, max_length=500)),
                ('year_of_release', models.DateField(default=None)),
            ],
        ),
    ]
