# Generated by Django 4.0.3 on 2022-03-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='manufacturer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='material',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='model',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo_file_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='year_of_release',
            field=models.DateField(),
        ),
    ]
